export const ROUTES = {
  HOME:                    '/',
  LOGIN:                   '/login',
  REGISTER:                '/register',
  VERIFY_OTP:              '/verify-email',
  FORGOT_PASSWORD:         '/forgot-password',
  RESET_PASSWORD:          '/reset-password',
  GOOGLE_SUCCESS:          '/auth/google/success',
  GOOGLE_VERIFY_OTP:       '/google/verify-otp',
  GOOGLE_COMPLETE_PROFILE: '/google/complete-profile',
  DASHBOARD:               '/dashboard',
  SETUP:                   '/setup',
  DICTATION:               '/dictation',
  RESULTS:                 '/results',
  SESSIONS:                '/sessions',          // ← session history + analytics
  PROFILE:                 '/profile',
  LEADERBOARD:             '/leaderboard',
  UPLOAD:                  '/upload',
  SETTINGS:                '/settings',
};
