/**
 * tts.js — Coqui TTS integration
 *
 * Replaces the previous ElevenLabs integration.
 * All speech is generated by the local Coqui TTS Python microservice
 * running at TTS_SERVICE_URL (default: http://localhost:5001).
 *
 * Voices are defined in tts_service/voices.py.
 * This file mirrors those constants so the Node.js layer can
 * validate/describe voice options without hitting the Python service.
 */

const { ttsServiceUrl } = require('./env');
const AppError = require('../utils/AppError');

// ── Voice catalogue (mirrors tts_service/voices.py) ──────────────────────────
const VOICES = {
  female: {
    american: { speakerId: 'p335', label: 'American Female' },
    british:  { speakerId: 'p225', label: 'British Female'  },
    indian:   { speakerId: 'p264', label: 'Indian Female'   },
  },
  male: {
    american: { speakerId: 'p292', label: 'American Male'   },
    british:  { speakerId: 'p226', label: 'British Male'    },
    indian:   { speakerId: 'p259', label: 'Indian Male'     },
  },
};

const VALID_GENDERS  = Object.keys(VOICES);
const VALID_ACCENTS  = ['american', 'british', 'indian'];
const DEFAULT_GENDER = 'female';
const DEFAULT_ACCENT = 'american';

/**
 * Call the Coqui TTS service and return a WAV Buffer.
 *
 * @param {string} text      - Text to synthesise
 * @param {string} gender    - 'female' | 'male'
 * @param {string} accent    - 'american' | 'british' | 'indian'
 * @returns {Promise<Buffer>} WAV audio buffer
 */
const generateSpeech = async (text, gender = DEFAULT_GENDER, accent = DEFAULT_ACCENT) => {
  if (!text?.trim()) throw new AppError('Text is required for TTS', 400);

  // Normalise / fallback
  const safeGender = VALID_GENDERS.includes(gender) ? gender : DEFAULT_GENDER;
  const safeAccent = VALID_ACCENTS.includes(accent)  ? accent : DEFAULT_ACCENT;

  const payload = {
    text:   text.trim(),
    gender: safeGender,
    accent: safeAccent,
  };

  let response;
  try {
    response = await fetch(`${ttsServiceUrl}/tts`, {
      method:  'POST',
      headers: { 'Content-Type': 'application/json' },
      body:    JSON.stringify(payload),
      // 30-second hard timeout — long sentences on CPU can take a moment
      signal:  AbortSignal.timeout(30_000),
    });
  } catch (err) {
    if (err.name === 'TimeoutError' || err.name === 'AbortError') {
      throw new AppError('TTS service timed out. Please try again.', 504);
    }
    throw new AppError(
      `Cannot reach TTS service at ${ttsServiceUrl}. Is it running? (${err.message})`,
      502
    );
  }

  if (!response.ok) {
    let detail = `TTS service returned ${response.status}`;
    try {
      const body = await response.json();
      if (body?.detail) detail = body.detail;
    } catch {/* ignore */}
    throw new AppError(detail, response.status === 503 ? 503 : 502);
  }

  const arrayBuffer = await response.arrayBuffer();
  if (!arrayBuffer.byteLength) {
    throw new AppError('TTS service returned empty audio', 502);
  }
  return Buffer.from(arrayBuffer);
};

/**
 * Check that the TTS service is alive.
 * Returns { ok: true, model, sample_rate } or throws.
 */
const healthCheck = async () => {
  try {
    const res = await fetch(`${ttsServiceUrl}/health`, {
      signal: AbortSignal.timeout(5_000),
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return await res.json();
  } catch (err) {
    throw new AppError(`TTS service unreachable: ${err.message}`, 502);
  }
};

module.exports = { generateSpeech, healthCheck, VOICES, VALID_GENDERS, VALID_ACCENTS };
